make: 
	gcc -o fsh fsh.c io.c util.c -Wall -Werror -g

val:
	echo "FAVOR NAO USAR MAKE PARA RODAR NOSSO CODIGO, OBRIGADO. FAVOR RODAR VALGRIND NA MAO"


run:
	echo "FAVOR NAO USAR MAKE PARA RODAR NOSSO CODIGO, OBRIGADO. FAVOR RODAR ./fsh"
